# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-22 07:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='first_showup',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='First Showup'),
        ),
    ]
