# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-22 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0002_participant_first_showup'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='others_can_see_me',
            field=models.BooleanField(default=False),
        ),
    ]
