# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-05-05 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0003_participant_others_can_see_me'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='dropout_date',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Dropout Date'),
        ),
    ]
