# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-05-11 13:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import enroll.models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0004_participant_dropout_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=enroll.models._new_token, max_length=32, unique=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='enroll.Participant')),
            ],
        ),
    ]
