# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-05-12 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0005_logintoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='email',
            field=models.CharField(max_length=400, unique=True),
        ),
    ]
